version = "0.7.1"
priority = 5

[plugin_meta]
name = "nonebot-plugin-moegoe"
description = "日韩中 VITS 模型拟声"
usage = """
moegoe
- 让[宁宁|爱瑠|芳乃|茉子|丛雨|小春|七海|妃爱|华乃|亚澄|诗樱|天梨|里|广梦|莉莉子]说日语：(日语)
- 让[Sua|Mimiru|Arin|Yeonhwa|Yuhwa|Seonbae]说韩语：(韩语)
- 让[派蒙|凯亚|安柏|丽莎|琴|香菱|枫原万叶|迪卢克|温迪|可莉|早柚|托马|芭芭拉|优菈|云堇|钟离|魈|凝光|雷电将军|北斗|甘雨|七七|刻晴|神里绫华|雷泽|神里绫人|罗莎莉亚|阿贝多|八重神子|宵宫|荒泷一斗|九条裟罗|夜兰|珊瑚宫心海|五郎|达达利亚|莫娜|班尼特|申鹤|行秋|烟绯|久岐忍|辛焱|砂糖|胡桃|重云|菲谢尔|诺艾尔|迪奥娜|鹿野院平藏]说(中文)
"""
unique_name = "moegoe"
example = "让派蒙说你好！旅行者。"
author = "yiyuiii <yiyuiii@foxmail.com>"

[download]
profile_url = "https://raw.githubusercontent.com/Yiyuiii/nonebot-plugin-moegoe/master/nonebot_plugin_moegoe/profile.toml"
proxy_url = "https://ghproxy.com/"

[jpapi]
url = "https://moegoe.azurewebsites.net/api/speak?text=${text}&id=${id}"
order = ["宁宁", "爱瑠", "芳乃", "茉子", "丛雨", "小春", "七海"]
regex = "^让(宁宁|爱瑠|芳乃|茉子|丛雨|小春|七海)说(?:日语|日文|日本语)(?:：|:)(.+)$"

[jp2api]
url = "https://moegoe.azurewebsites.net/api/speak2?text=${text}&id=${id}"
order = ["妃爱", "华乃", "亚澄", "诗樱", "天梨", "里", "广梦", "莉莉子"]
regex = "^让(妃爱|华乃|亚澄|诗樱|天梨|里|广梦|莉莉子)说(?:日语|日文|日本语)(?:：|:)(.+)$"

[krapi]
url = "https://moegoe.azurewebsites.net/api/speakkr?text=${text}&id=${id}"
order = ["Sua", "Mimiru", "Arin", "Yeonhwa", "Yuhwa", "Seonbae"]
regex = "^让(Sua|Mimiru|Arin|Yeonhwa|Yuhwa|Seonbae)说(?:韩语|韩文|韩国语)(?:：|:)(.+)$"

[cnapi]
url = "https://genshin.azurewebsites.net/api/speak?format=mp3&text=${text}&id=${id}"
order = ["派蒙", "凯亚", "安柏", "丽莎", "琴", "香菱", "枫原万叶", "迪卢克", "温迪", "可莉", "早柚", "托马", "芭芭拉", "优菈", "云堇", "钟离", "魈", "凝光", "雷电将军", "北斗", "甘雨", "七七", "刻晴", "神里绫华", "戴因斯雷布", "雷泽", "神里绫人", "罗莎莉亚", "阿贝多", "八重神子", "宵宫", "荒泷一斗", "九条裟罗", "夜兰", "珊瑚宫心海", "五郎", "散兵", "女士", "达达利亚", "莫娜", "班尼特", "申鹤", "行秋", "烟绯", "久岐忍", "辛焱", "砂糖", "胡桃", "重云", "菲谢尔", "诺艾尔", "迪奥娜", "鹿野院平藏"]
regex = "^让(派蒙|凯亚|安柏|丽莎|琴|香菱|枫原万叶|迪卢克|温迪|可莉|早柚|托马|芭芭拉|优菈|云堇|钟离|魈|凝光|雷电将军|北斗|甘雨|七七|刻晴|神里绫华|雷泽|神里绫人|罗莎莉亚|阿贝多|八重神子|宵宫|荒泷一斗|九条裟罗|夜兰|珊瑚宫心海|五郎|达达利亚|莫娜|班尼特|申鹤|行秋|烟绯|久岐忍|辛焱|砂糖|胡桃|重云|菲谢尔|诺艾尔|迪奥娜|鹿野院平藏)说(.+)$"
replace = [[',', '，'], ['.', '。'], ['!', '！'], ['?', '？'], ['0', '零'], ['1', '一'], ['2', '二'], ['3', '三'], ['4', '四'], ['5', '五'], ['6', '六'], ['7', '七'], ['8', '八'], ['9', '九'], ]
